## EXPERIMENT 2
### Numerical Python (NumPy)

### Name: Samar, Mariane Izley V. 
### Section: 2ECE-D                                                                    
Date Submitted: Sept. 5, 2024

###

# NORMALIZATION PROBLEM

In [21]:
import numpy as np #importing the numpy library in python to make it easier

X = np.random.random((5,5)) #creating a 5x5 ndarray
mean = X.mean(axis = 0) #normalizing the array
standard = X.std(axis=0) 
X_normalized = (X-mean) / standard
np.save('X_normalized.np', X_normalized) #saving the normalized ndarray

In [73]:
#printing the original and normalized ndarrays
print("\nOriginal Array:\n", X)
print("\n\nNormalized Array:\n", X_normalized)


Original Array:
 [[0.64156511 0.1230184  0.60655316 0.04444247 0.72318344]
 [0.16656711 0.81935564 0.40349127 0.31687136 0.92030582]
 [0.53566196 0.24132417 0.03997732 0.68015088 0.40422194]
 [0.81209019 0.59454981 0.82132868 0.80160981 0.42817169]
 [0.74452281 0.41877561 0.17623347 0.21379061 0.49052937]]


Normalized Array:
 [[ 0.27086819 -1.27435459  0.69712636 -1.28587976  0.65379783]
 [-1.82174993  1.5303828  -0.0213186  -0.33117378  1.64592412]
 [-0.19569133 -0.79783747 -1.30745249  0.9419112  -0.95155054]
 [ 1.02212161  0.62490012  1.4570149   1.36755463 -0.8310103 ]
 [ 0.72445146 -0.08309086 -0.82537017 -0.69241229 -0.51716112]]


###

# DIVISIBLE BY 3 PROBLEM

In [76]:
import numpy as np  #importing the numpy library in python to make it easier

A = np.arange(1, 101).reshape(10, 10)**2 #create the 10x10 ndarray with the squares of the first 100 integers
div_by_3 = [A%3 == 0] #formula for getting the elements that are divisible by 3
np.save('div_by_3.npy', div_by_3) #saving the div_by_3.npy

In [78]:
print("\nOriginal Array: \n", A) #printing the original and the elements divisible by 3
print("\n\nThe elements divisible by 3: \n", div_by_3)


Original Array: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


The elements divisible by 3: 
 [array([[False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False