## EXPERIMENT 2
### Numerical Python (NumPy)

### Name: Samar, Mariane Izley V. 
### Section: 2ECE-D                                                                    
Date Submitted: Sept. 5, 2024

###

# NORMALIZATION PROBLEM

In [86]:
import numpy as np #importing the numpy library in python to make it easier

X = np.random.random((5,5)) #creating a 5x5 ndarray
mean = X.mean() #normalizing the array
standard = X.std() 
X_normalized = (X-mean) / standard
np.save('X_normalized.np', X_normalized) #saving the normalized ndarray

In [88]:
#printing the original and normalized ndarrays
print("\nOriginal Array:\n", X)
print("\n\nNormalized Array:\n", X_normalized)


Original Array:
 [[0.35370423 0.14102794 0.21697392 0.75967071 0.85414712]
 [0.88626003 0.93113603 0.24329288 0.98538888 0.43856947]
 [0.5646169  0.18362944 0.09747255 0.43692319 0.89591563]
 [0.9087983  0.26234681 0.8902858  0.38585981 0.30586228]
 [0.2166359  0.74966693 0.01217931 0.45349488 0.5684197 ]]


Normalized Array:
 [[-0.51401478 -1.2148348  -0.96457433  0.82374337  1.13506608]
 [ 1.24088592  1.38876325 -0.87784696  1.56753956 -0.23436318]
 [ 0.18099369 -1.0744525  -1.35836039 -0.23978809  1.27270348]
 [ 1.31515499 -0.81505966  1.25415182 -0.40805432 -0.6716656 ]
 [-0.96568819  0.79077847 -1.63942233 -0.18518036  0.19352486]]


###

# DIVISIBLE BY 3 PROBLEM

In [76]:
import numpy as np  #importing the numpy library in python to make it easier

A = np.arange(1, 101).reshape(10, 10)**2 #create the 10x10 ndarray with the squares of the first 100 integers
div_by_3 = [A%3 == 0] #formula for getting the elements that are divisible by 3
np.save('div_by_3.npy', div_by_3) #saving the div_by_3.npy

In [78]:
print("\nOriginal Array: \n", A) #printing the original and the elements divisible by 3
print("\n\nThe elements divisible by 3: \n", div_by_3)


Original Array: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


The elements divisible by 3: 
 [array([[False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
         True],
       [False, False,  True, False, False,  True, False